/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayerGUI2.java
 *
 * Created on 9-Jan-2018, 9:57:10 PM
 */
package com.ferafln.war.gui.bottom;

import com.ferafln.war.Player;
import com.ferafln.war.territorio.util.Observer;

/**
 *
 * @author feraf
 */
public class PlayerGUI extends javax.swing.JPanel implements Observer{
    private final Player player;
    private Player turnPlayer;
    /** Creates new form PlayerGUI2 */
    public PlayerGUI(Player player, int order) {
        this.player = player;
        initComponents();
        lblNamePlayer.setText(player.getName());
        lblExtraTroops.setText(""+player.getExtraTroops());
        lblColor.setIcon(player.getTroop().getImagem());
        setBounds(0, 0, 283, 70);
        setLocationPlayer(order);
    }

    public Player getPlayer() {
        return player;
    }

    public void setTurnPlayer(Player turnPlayer) {
        this.turnPlayer = turnPlayer;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNamePlayer = new javax.swing.JLabel();
        lblExtraTroops = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();

        setLayout(null);
        add(lblNamePlayer);
        lblNamePlayer.setBounds(121, 11, 152, 19);
        add(lblExtraTroops);
        lblExtraTroops.setBounds(121, 36, 152, 14);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Name: ");
        add(jLabel1);
        jLabel1.setBounds(10, 16, 105, 14);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Extra Troops: ");
        add(jLabel2);
        jLabel2.setBounds(10, 36, 105, 14);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Color: ");
        add(jLabel3);
        jLabel3.setBounds(10, 56, 105, 14);
        add(lblColor);
        lblColor.setBounds(121, 56, 71, 14);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblExtraTroops;
    private javax.swing.JLabel lblNamePlayer;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        lblExtraTroops.setText(""+player.getExtraTroops());
    }

    private void setLocationPlayer(int order) {
        switch (order){
            case 1: setLocation(0, 520);
                break;
            case 2: setLocation(297, 520);
                break;
            case 3: setLocation(570, 520);
                break;
        }
    }

    
}
