/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayerPanelGUI.java
 *
 * Created on 11-Jan-2018, 10:11:08 PM
 */
package com.ferafln.war.gui.bottom;

import com.ferafln.war.Player;
import com.ferafln.war.exception.WarException;
import com.ferafln.war.gui.FontDefaultGame;
import com.ferafln.war.gui.bottom.leftpanel.LeftPlayerPanelAbstract;
import com.ferafln.war.gui.bottom.leftpanel.LeftPlayerPanelFactory;
import com.ferafln.war.gui.bottom.rightpanel.RightPlayerPanelAbstract;
import com.ferafln.war.gui.bottom.rightpanel.RightPlayerPanelFactory;
import com.ferafln.war.gui.util.PathImagesGUIEnum;
import com.ferafln.war.territorio.util.Observer;
import com.ferafln.war.territorio.util.StepRoundEnum;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author feraf
 */
public class PlayerPanelGUI extends javax.swing.JPanel implements Observer{

    private final ImageIcon bottom;
    private Player playerRound;
    private PlayerPanel playerPanel;
    private LeftPlayerPanelAbstract leftPanel;
    private LeftPlayerPanelFactory leftFactory;
    private RightPlayerPanelAbstract rightPanel;
    private RightPlayerPanelFactory rightFactory;

    /** Creates new form PlayerPanelGUI */
    public PlayerPanelGUI(PlayerPanel playerPanel) {
        bottom = new ImageIcon(PathImagesGUIEnum.IMAGE_BOTTOM.getPath());
        initComponents();
        btnObjectiveCard.setIcon(new ImageIcon(PathImagesGUIEnum.OBJECTIVE_CARD.getPath()));
        //jButton1 = tb;
        this.playerPanel = playerPanel;
//        this.getLeftInfoPanel();
//        this.getRightInfoPanel();
        this.setPlayerRound();
        jLabel1.setVisible(false);
        setBounds(0, 478, 1024, 300);
        this.add(leftPanel);
    }

    private void getRightInfoPanel() {
        if (this.rightFactory == null) {
            this.rightFactory = new RightPlayerPanelFactory();
        } else {
            this.remove(rightPanel);
        }
        rightPanel = rightFactory.getInfoPanel(playerPanel);
        this.add(rightPanel);
        repaint();
    }
    
    private void getLeftInfoPanel() {
        if (this.leftFactory == null) {
            this.leftFactory = new LeftPlayerPanelFactory();
        } else {
            this.remove(leftPanel);
        }
        leftPanel = leftFactory.getInfoPanel(playerPanel);
        this.add(leftPanel);
        repaint();
    }

    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(bottom.getImage(), 0, 0, null);
    }

    private void setPlayerRound() {
        this.playerRound = this.playerPanel.getRoundPlayer();
        getLeftInfoPanel();
        getRightInfoPanel();
        rightPanel.update();
        leftPanel.update();
        lblNamePlayer.setText(playerRound.getName());
//        lblStatus.setText(playerRound.getStepRoundEnum().toString());
        lblRound.setText("" + playerPanel.getRound());
        btnAttack.setEnabled(StepRoundEnum.ATTACK.equals(playerRound.getStepRoundEnum()));
        btnDefend.setEnabled(StepRoundEnum.ATTACK.equals(playerRound.getStepRoundEnum()));
    }

//    public Observer getObserver() {
//        return leftPanel;
//    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNamePlayer = new javax.swing.JLabel();
        btnDefend = new javax.swing.JButton();
        btnAttack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnObjectiveCard = new javax.swing.JButton();
        lblRound = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        lblNamePlayer.setFont(new FontDefaultGame(14));
        lblNamePlayer.setForeground(new java.awt.Color(255, 255, 255));
        lblNamePlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNamePlayer.setText("Fernando");
        add(lblNamePlayer);
        lblNamePlayer.setBounds(445, 62, 135, 30);

        btnDefend.setBackground(new java.awt.Color(255, 255, 51));
        add(btnDefend);
        btnDefend.setBounds(512, 175, 28, 25);

        btnAttack.setBackground(new java.awt.Color(255, 51, 51));
        add(btnAttack);
        btnAttack.setBounds(482, 175, 28, 25);

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(480, 220, 60, 23);

        btnObjectiveCard.setBorderPainted(false);
        btnObjectiveCard.setContentAreaFilled(false);
        btnObjectiveCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObjectiveCardActionPerformed(evt);
            }
        });
        add(btnObjectiveCard);
        btnObjectiveCard.setBounds(10, 95, 210, 185);

        lblRound.setFont(new java.awt.Font("Tahoma", 0, 24));
        lblRound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRound.setText("1");
        add(lblRound);
        lblRound.setBounds(480, 100, 65, 65);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\feraf\\OneDrive\\Documentos\\NetBeansProjects\\War\\Images\\bottom.png")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, -4, 1050, 300);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        this.playerPanel.nextStep();
        setPlayerRound();
        if(this.playerPanel.getRound()==0){
            playerPanel.setVisibleObjective(true);
        }
    } catch (WarException ex) {
        //TODO: Implements this
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void btnObjectiveCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObjectiveCardActionPerformed
    playerPanel.setVisibleObjective(true);
}//GEN-LAST:event_btnObjectiveCardActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttack;
    private javax.swing.JButton btnDefend;
    private javax.swing.JButton btnObjectiveCard;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNamePlayer;
    private javax.swing.JLabel lblRound;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        leftPanel.update();
        rightPanel.update();
    }
}
