/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJPanel.java
 *
 * Created on 15-Jan-2018, 7:37:23 PM
 */
package com.ferafln.war.gui.bottom.rightpanel;

import com.ferafln.war.Player;
import com.ferafln.war.gui.FontDefaultGame;
import com.ferafln.war.gui.bottom.PlayerPanel;

/**
 *
 * @author feraf
 */
public class RightPanelDistTroops extends RightPlayerPanelAbstract {

    public RightPanelDistTroops(PlayerPanel playerPanel) {
        super(playerPanel);
        initComponents();
    }

//    public void setRoundPlayer() {
//    }

    /** Creates new form NewJPanel */
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(null);

        jLabel4.setFont(new FontDefaultGame());
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html>\nClique com o botão esquerdo para adicionar exercito e botão direito para remover \n<html/>");
        add(jLabel4);
        jLabel4.setBounds(0, 0, 210, 70);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        Player playerRound = this.getPlayerPanel().getRoundPlayer();
       
    }
}
