/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MapPanelGUI.java
 *
 * Created on 11-Jan-2018, 9:27:16 PM
 */
package com.ferafln.war.gui;

import com.ferafln.war.gui.util.PathImagesGUIEnum;
import java.awt.Graphics;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author feraf
 */
public class MapPanelGUI extends javax.swing.JPanel {
    private final ImageIcon map;
    /** Creates new form MapPanelGUI */
    public MapPanelGUI() {
        this.map = new ImageIcon(PathImagesGUIEnum.IMAGE_MAP.getPath());
        initComponents();
        setSize(1024, 766);
    }

    protected void paintComponent(Graphics g) {

        super.paintComponent(g);
        g.drawImage(map.getImage(), 0, 0, null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
