/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ObjectiveDialog.java
 *
 * Created on 28-Jan-2018, 5:29:53 PM
 */
package com.ferafln.war.gui;

import com.ferafln.war.gui.util.PathImagesGUIEnum;
import com.ferafln.war.gui.util.PropFilesGUIEnum;
import com.ferafln.war.territorio.util.Props;
import java.awt.Color;
import java.awt.Frame;
import java.util.Properties;
import javax.swing.ImageIcon;

/**
 *
 * @author feraf
 */
public class ObjectiveDialog extends javax.swing.JDialog {

    private final ImageIcon map;
    private final Frame parent;
    /** Creates new form ObjectiveDialog */
    public ObjectiveDialog(Frame parent, boolean modal) {
        super(parent, modal);
        this.parent=parent;
        this.map = new ImageIcon(PathImagesGUIEnum.WINDOW_OBJECTIVE.getPath());
        initComponents();
        getRootPane().setOpaque(false);
        getContentPane ().setBackground (new Color (0, 0, 0, 0));
        setBackground (new Color (0, 0, 0, 0));
        setVisible(false);
        setBounds(0, 0, 265, 316);
        lblBorder.setSize(265, 316);
        lblBorder.setIcon(map);
        center();
    }

    private void center() {
        int width=parent.getSize().width;
        int hight=parent.getSize().height-160;
        int myWidth = this.getSize().width;
        int myHight = this.getSize().height;
        int x = this.parent.getLocation().x+((width / 2) - (myWidth / 2));
        int y = this.parent.getLocation().y+((hight / 2) - (myHight / 2));
        this.setLocation(x , y);
        lblCard.setLocation(12, 34);
    }
    
    public void show(int idObjective) {
        center();
        Properties p = Props.getProperties(PropFilesGUIEnum.OBJECTIVE_IMAGE.getPath());
        String name = p.getProperty("" + idObjective).trim();
        lblCard.setIcon(new ImageIcon(PathImagesGUIEnum.getRoot() + name));
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblBorder = new javax.swing.JLabel();
        lblCard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jButton1.setFont(new FontDefaultGame());
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ok");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(109, 288, 50, 23);

        lblBorder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBorder.setIcon(new javax.swing.ImageIcon("C:\\Users\\feraf\\OneDrive\\Documentos\\NetBeansProjects\\War\\Images\\objetivos\\ObjectiveWindow.png")); // NOI18N
        lblBorder.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(lblBorder);
        lblBorder.setBounds(0, 0, 270, 316);

        lblCard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblCard);
        lblCard.setBounds(0, 0, 242, 260);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 300, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.setVisible(false);
//    for (Component cp : panelFather.getComponents()) {
//        cp.setEnabled(true);
//    }
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBorder;
    private javax.swing.JLabel lblCard;
    // End of variables declaration//GEN-END:variables
}
