/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tabuleiro.java
 *
 * Created on 9-Jan-2018, 9:46:55 PM
 */
package com.ferafln.war.gui;

import com.ferafln.war.gui.bottom.PlayerPanel;
import com.ferafln.war.gui.bottom.PlayerPanelGUI;
import com.ferafln.war.gui.bottom.PlayerDisplay;
import com.ferafln.war.Player;
import com.ferafln.war.Tabuleiro;
import com.ferafln.war.exception.WarException;
import com.ferafln.war.exercito.Exercito;
import com.ferafln.war.gui.util.PathImagesGUIEnum;
import com.ferafln.war.territorio.Territory;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author feraf
 */
public class TabuleiroGUI extends javax.swing.JFrame implements PlayerPanel {

    private Tabuleiro tabuleiro;
//    private List<PlayerGUI> playerGUIs;
    private List<TerritoryGUI> territoryGUIs;
    private ObjectiveDialog objectivePanel;
//    private PlayerPanel playerPanel;
    private MapPanelGUI pnlMap;
    private PlayerPanelGUI playerPanelGUI;
//    private static String fileTroops = System.getProperty("user.dir")+File.separator + "Images" + File.separator+"Exercitos"+ File.separator ;//TODO remove this after;;

    /** Creates new form Tabuleiro */
    public TabuleiroGUI() throws WarException {
//        playerPanel = new PlayerDisplay(this);
        initComponents();

    }

    public void start(List<Player> players) throws WarException {
        tabuleiro = new Tabuleiro(players);
        tabuleiro.iniciarPartida();
        pnlMap = new MapPanelGUI();
        this.objectivePanel = new ObjectiveDialog(this, true);
        playerPanelGUI = new PlayerPanelGUI(this);
        this.add(pnlMap);
        pnlMap.add(playerPanelGUI);
        setTerritorys();
        setVisible(true);
        setVisibleObjective(true);
    }

    public Tabuleiro getTabuleiro() {
        return tabuleiro;
    }

    private void setTerritorys() {
        this.territoryGUIs = new ArrayList<>();
        List<Territory> l = tabuleiro.getTerritorys();
        for (Territory territory : l) {
            TerritoryGUI territoryGUI = new TerritoryGUI(territory);
            territoryGUI.setObserver(playerPanelGUI);
            territoryGUIs.add(territoryGUI);
            pnlMap.add(territoryGUI);
        }
    }

    public void setVisibleObjective(boolean b) {
        if (true) {
            objectivePanel.show(tabuleiro.getRoundPlayer().getObjetive().getId());
        } else {
            objectivePanel.setVisible(b);
        }
    }

    @Override
    public Player getRoundPlayer() {
        return getTabuleiro().getRoundPlayer();
    }

    @Override
    public int getRound() {
        return getTabuleiro().getRound();
    }

    @Override
    public void nextStep() throws WarException {
        getTabuleiro().nextStep();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1040)/2, (screenSize.height-806)/2, 1040, 806);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabuleiroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabuleiroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabuleiroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabuleiroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
//                    0=white
//1=black
//2=yellow
//3=green
//4=blue
//5=red
                    Player p = new Player();
                    p.setName("Fernando");
                    Exercito e = new Exercito(5, "red");
                    e.setIamgem(new ImageIcon(PathImagesGUIEnum.RED_TROOP.getPath()));
                    p.setTroop(e);

                    Player p1 = new Player();
                    p1.setName("Lina");
                    e = new Exercito(4, "blue");
                    e.setIamgem(new ImageIcon(PathImagesGUIEnum.BLUE_TROOP.getPath()));
                    p1.setTroop(e);

                    Player p2 = new Player();
                    p2.setName("Gisele");
                    e = new Exercito(0, "white");
                    e.setIamgem(new ImageIcon(PathImagesGUIEnum.WHITE_TROOP.getPath()));
                    p2.setTroop(e);

                    Player p3 = new Player();
                    p3.setName("Lucas");
                    e = new Exercito(3, "green");
                    e.setIamgem(new ImageIcon(PathImagesGUIEnum.GREEN_TROOP.getPath()));
                    p3.setTroop(e);

                    new TabuleiroGUI().start(Arrays.asList(p1, p2, p, p3));
                } catch (WarException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
