/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LeftPanelAttack.java
 *
 * Created on 16-Jan-2018, 6:47:33 PM
 */
package com.ferafln.war.gui.bottom.panel;

import com.ferafln.war.Player;
import com.ferafln.war.gui.FontDefaultGame;
import com.ferafln.war.gui.bottom.PlayerPanel;

/**
 *
 * @author feraf
 */
public class LeftPanelAttack extends InfoPlayerAbstract {

    public LeftPanelAttack(PlayerPanel playerPanel) {
        super(playerPanel);
        initComponents();
    }

    /** Creates new form LeftPanelAttack */

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNameTerritory = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAmountTroops = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        lblNameTerritory.setFont(new FontDefaultGame());
        lblNameTerritory.setForeground(new java.awt.Color(255, 255, 255));
        lblNameTerritory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameTerritory.setText("Choose one territory to attack");
        add(lblNameTerritory);
        lblNameTerritory.setBounds(0, 0, 210, 17);

        lbl1.setFont(new FontDefaultGame());
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setText("Troops:");
        add(lbl1);
        lbl1.setBounds(5, 20, 50, 17);

        jLabel2.setFont(new FontDefaultGame());
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Player:");
        add(jLabel2);
        jLabel2.setBounds(5, 40, 50, 17);

        lblAmountTroops.setFont(new FontDefaultGame());
        lblAmountTroops.setForeground(new java.awt.Color(255, 255, 255));
        lblAmountTroops.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblAmountTroops);
        lblAmountTroops.setBounds(45, 20, 26, 17);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lblAmountTroops;
    private javax.swing.JLabel lblNameTerritory;
    // End of variables declaration//GEN-END:variables

//    @Override
//    public void setRoundPlayer() {
//        throw new UnsupportedOperationException("Not supported yet.");
//    }

    @Override
    public void update() {
        Player playerRound = this.getPlayerPanel().getRoundPlayer();
        if(playerRound.getAttackTerritory()!=null){
            lblAmountTroops.setText("" + playerRound.getAttackTerritory().getAmountTroops());
            lblNameTerritory.setText(playerRound.getAttackTerritory().getName());
        }
    }
}
